using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
//Siempre
using Oracle.ManagedDataAccess.Client;
using Oracle.ManagedDataAccess.Types;
using System.Configuration;
using System.Data;
using Controller;
using CapaDatosAccess;
using ToastNotifications;
using ToastNotifications.Lifetime;
using ToastNotifications.Position;
using ToastNotifications.Messages;
using ToastNotifications.Core;

namespace EscritorioFerme
{
    /// <summary>
    /// Interaction logic for UserControlColaboradores.xaml
    /// </summary>
    public partial class UserControlColaboradores : UserControl
    {
        public UserControlColaboradores()
        {
            InitializeComponent();

        }
        Notifier notifier = new Notifier(cfg =>
        {
            cfg.PositionProvider = new PrimaryScreenPositionProvider(
                corner: Corner.TopRight,
                offsetX: 63,
                offsetY: 50);

            cfg.LifetimeSupervisor = new TimeAndCountBasedLifetimeSupervisor(
                notificationLifetime: TimeSpan.FromSeconds(5),
                maximumNotificationCount: MaximumNotificationCount.FromCount(5));

            cfg.Dispatcher = Application.Current.Dispatcher;
            cfg.DisplayOptions.TopMost = true; // set the option to show notifications over other windows
            cfg.DisplayOptions.Width = 500; // set the notifications width
        });
        MessageOptions options = new MessageOptions
        {
            FontSize = 25, // set notification font size
            ShowCloseButton = false, // set the option to show or hide notification close button
            FreezeOnMouseEnter = true, // set the option to prevent notification dissapear automatically if user move cursor on it
        };
        public void Cargatabla()
        {
            try
            {
                UsuariosDAO usu = new UsuariosDAO();
                var lista = usu.listaUsu();
                dataGrid.ItemsSource = lista;
            }
            catch (Exception)
            {

                throw;
            }
        }

        private void button_Click(object sender, RoutedEventArgs e)
        {
            AgregarColaboradorWpf cola = new AgregarColaboradorWpf();
            cola.Show();

        }

        private void dataGrid_Loaded(object sender, RoutedEventArgs e)
        {
            Cargatabla();
        }



        private void dataGrid_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            object selectUser = dataGrid.SelectedItem;
            AgregarColaboradorWpf cola = new AgregarColaboradorWpf();
            
            //obtiene los datos del datagrid
            string Rut = (dataGrid.SelectedCells[0].Column.GetCellContent(selectUser) as TextBlock).Text;
            string nombre = (dataGrid.SelectedCells[1].Column.GetCellContent(selectUser) as TextBlock).Text;
            string apellido = (dataGrid.SelectedCells[2].Column.GetCellContent(selectUser) as TextBlock).Text;
            string cargo = (dataGrid.SelectedCells[4].Column.GetCellContent(selectUser) as TextBlock).Text;
            string usunom = (dataGrid.SelectedCells[5].Column.GetCellContent(selectUser) as TextBlock).Text;
            string pass = (dataGrid.SelectedCells[6].Column.GetCellContent(selectUser) as TextBlock).Text;

            if (Rut == "" || nombre == "" || apellido == "" || cargo == "" || usunom == "" || pass == "")
            {
                notifier.ShowInformation("No ha seleccionado una fila correcta", options);
            }
            else
            {
                ColaboradoresDAO coldao = new ColaboradoresDAO();
                if (coldao.ExisteCola(Rut)==true)
                {
                    notifier.ShowInformation("Este usuario ya tiene permisos de colaborador", options);
                    cola.Show();
                    cola.btnAgregarUsu.Visibility = Visibility.Collapsed;
                }
                else
                {
                    cola.txtRut.Text = Rut;
                    cola.txtNombre.Text = nombre + " " + apellido;
                    cola.txtCargo.Text = cargo;
                    cola.txtUsuario.Text = usunom;
                    cola.txtContra.Text = pass;

                    cola.Show();
                }
                
                
                //set los datos dentro de los combobox de la otra ventana
                
            }
            
            
        }

        private void textBox_TextChanged(object sender, TextChangedEventArgs e)
        {

        }

        private void dataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
           
        }
    }
}